---
- hosts: "master, node"
  remote_user: cmc
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: Create containerd config file
       file:
         path: "/etc/yum.repos.d/kubernetes.repo"
         state: "touch"

     - name: Add k8s repo
       blockinfile:
         path: "/etc/yum.repos.d/kubernetes.repo"
         block: |
               [kubernetes]
               name=Kubernetes
               baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
               enabled=1
               gpgcheck=1
               repo_gpgcheck=1
               gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
               
     - name: install k8s
       shell: |
              sudo yum -y install epel-release vim git curl wget kubelet kubeadm kubectl --disableexcludes=kubernetes
     
     - name: modprobe SELINUX ans Swap
       shell: |
               sudo setenforce 0
               sudo sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
               sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
               sudo swapoff -a
               sudo modprobe overlay
               sudo modprobe br_netfilter
     
     - name: Create conf for containerd
       file:
         path: "/etc/sysctl.d/kubernetes.conf"
         state: "touch"
         
     - name: Add conf for containerd
       blockinfile:
         path: "/etc/sysctl.d/kubernetes.conf"
         block: |
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1

     - name: Apply new settings
       shell: |
               sudo sysctl --system
               
     - name: Create containerd config file
       file:
         path: "/etc/modules-load.d/containerd.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/modules-load.d/containerd.conf"
         block: |
               overlay
               br_netfilter

     - name: modprobe
       shell: |
               sudo modprobe overlay
               sudo modprobe br_netfilter

     - name: Set system configurations for Kubernetes networking
       file:
         path: "/etc/sysctl.d/kubernetes.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/sysctl.d/kubernetes.conf"
         block: |
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                net.bridge.bridge-nf-call-ip6tables = 1

     - name: Apply new settings
       command: sudo sysctl --system

     - name: install containerd
       shell: |
               sudo yum install -y yum-utils device-mapper-persistent-data lvm2
               sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
               sudo yum update -y && yum install -y containerd.io
               sudo mkdir -p /etc/containerd
               sudo containerd config default > /etc/containerd/config.toml
               sudo systemctl restart containerd
               sudo systemctl enable containerd
               sudo systemctl disable --now firewalld