- hosts: node
  become: yes
  gather_facts: yes

  tasks:
     - name: Enable kubelet and pull kubeadm images
       shell: |
               hostnamectl set-hostname node
               sudo systemctl enable kubelet
               
     - name: Copy join command from Ansiblehost to the worker nodes.
       become: yes
       copy:
         src: /etc/ansible/kubernetes_join_command
         dest: /tmp/kubernetes_join_command
         mode: 0777

     - name: Join the Worker nodes to the cluster.
       become: yes
       command: sh /tmp/kubernetes_join_command
       register: joined_or_not